version: '3.8'
services:
  mysql-inventory:
    container_name: mysql-inventory
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: inventory-service
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-inventory-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-inventory-data:
